### ISSUE TITLE
بررسی شد

### ISSUE THREAD

**Issue by aloneStarDev** [MohammadMoeinKeyvani/Main-Class-Projects#1]
واقعا ممنون شما اولین نفری بودید که تمام ساختار های  پوشه بندی رو رعایت کردید
و البته تمرین ها هم اوکی بود ...فقط دیزاین پترن ها مونده که تا هفته بعد ارسال می کنید

**Comment by MohammadMoeinKeyvani** [comment]
ممنون سلطان،وظیفه بود🙂
